#Original Filename Mappings - 2026-01-18T21:52:48.996070600
#Sun Jan 18 21:52:48 CST 2026
chat_1768740394619_amsw3y6da=SAM-I2V_Efficiently_Upgrading_SAM_for_Promptable_Video_Segmentation-1-2.pdf
chat_1768741133210_8wnk4y1bm=SAM-I2V_Efficiently_Upgrading_SAM_for_Promptable_Video_Segmentation-1-2.pdf
chat_1768741745015_f5cjd9gd3=SAM-I2V_Efficiently_Upgrading_SAM_for_Promptable_Video_Segmentation-1-2.pdf
chat_1768742007703_lmi7pnbdj=计算机与信息学院（人工智能学院）2026年“挑战杯”大学生创业计划竞赛院内选拔赛拟推荐作品名单.pdf
chat_1768742036293_ys2zr32et=SAM-I2V_Efficiently_Upgrading_SAM_for_Promptable_Video_Segmentation-1-2.pdf
chat_1768742045651_s7tuzrrcs=计算机与信息学院（人工智能学院）2026年“挑战杯”大学生创业计划竞赛院内选拔赛拟推荐作品名单.pdf
chat_1768742689547_cd5nfh6hs=SAM-I2V_Efficiently_Upgrading_SAM_for_Promptable_Video_Segmentation-1-2.pdf
chat_1768742888996_q0zwtyx1h=SAM-I2V_Efficiently_Upgrading_SAM_for_Promptable_Video_Segmentation-1-2.pdf
chat_1768743045819_x58xyg7e9=SAM-I2V_Efficiently_Upgrading_SAM_for_Promptable_Video_Segmentation-1-2.pdf
chat_1768743406227_3khwv73wy=SAM-I2V_Efficiently_Upgrading_SAM_for_Promptable_Video_Segmentation-1-2.pdf
chat_1768743820996_bjyszbbr9=SAM-I2V_Efficiently_Upgrading_SAM_for_Promptable_Video_Segmentation-1-2.pdf
chat_1768743856944_0u2ftbgx7=计算机与信息学院（人工智能学院）2026年“挑战杯”大学生创业计划竞赛院内选拔赛拟推荐作品名单.pdf
chat_1768743936288_o32m2am2j=计算机与信息学院（人工智能学院）2026年“挑战杯”大学生创业计划竞赛院内选拔赛拟推荐作品名单.pdf
chat_1768744278725_vewvrs4iw=SAM-I2V_Efficiently_Upgrading_SAM_for_Promptable_Video_Segmentation-1-2.pdf
